CREATE TABLE IF NOT EXISTS cart (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  BATCHID VARCHAR(255) NOT NULL,
  BARCODE VARCHAR(255) NOT NULL,
  DESCRIPTION VARCHAR(255) NOT NULL,
  BRAND VARCHAR(255) NOT NULL,
  UNIT VARCHAR(255) NOT NULL,
  QTY DECIMAL(12,2) NOT NULL DEFAULT 0,
  PRICE DECIMAL(12,2) NOT NULL DEFAULT 0,
  TOTAL DECIMAL(12,2) NOT NULL DEFAULT 0,
  USERID INT NOT NULL,
  UNIQUE KEY cart_user_line (USERID, BARCODE, BATCHID)
);

